---
abstract: 'Gather package and POD information from perl module files'
author:
  - 'Ken Williams <kwilliams@cpan.org>, Randy W. Sims <RandyS@ThePierianSpring.org>'
build_requires:
  Carp: 0
  Config: 0
  Cwd: 0
  Data::Dumper: 0
  Exporter: 0
  ExtUtils::MakeMaker: 0
  File::Basename: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  IO::File: 0
  Test::More: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.132620'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Metadata
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  File::Find: 0
  File::Spec: 0
  IO::File: 0
  perl: 5.006
  strict: 0
  vars: 0
  version: 0.87
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Module-Metadata
  repository: git://git.shadowcat.co.uk/p5sagit/Module-Metadata.git
version: 1.000019
