---
abstract: 'Gather package and POD information from perl module files'
author:
  - 'Ken Williams <kwilliams@cpan.org>, Randy W. Sims <RandyS@ThePierianSpring.org>'
build_requires:
  Cwd: '0'
  File::Basename: '0'
  File::Path: '0'
  File::Temp: '0'
  IO::File: '0'
  Test::More: '0.82'
  vars: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9701, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Module-Metadata
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  File::Find: '0'
  File::Spec: '0'
  perl: '5.006'
  strict: '0'
  version: '0.87'
  warnings: '0'
resources:
  IRC: irc://irc.perl.org/#toolchain
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Module-Metadata
  homepage: https://metacpan.org/pod/Module::Metadata
  repository: https://github.com/Perl-Toolchain-Gang/Module-Metadata
version: '1.000021'
